version: '3'
services:
  messages:
    image: golang:1.9.2
    working_dir: /go/src/github.com/lozaeric/dupin/messages-api
    command: go run main.go
    ports:
     - "8080:8080"
    volumes:
     - ./messages-api:/go/src/github.com/lozaeric/dupin/messages-api
    environment:
     - ENV=production
     - SECRET_JWT='in the hall of the mountain king'
    depends_on:
     - mongo
     - redis
  auth:
    image: golang:1.9.2
    working_dir: /go/src/github.com/lozaeric/dupin/auth-api
    command: go run main.go
    ports:
     - "8081:8080"
    volumes:
     - ./auth-api:/go/src/github.com/lozaeric/dupin/auth-api
    environment:
     - ENV=production
     - SECRET_JWT='in the hall of the mountain king'
    depends_on:
     - redis
  users:
    image: golang:1.9.2
    working_dir: /go/src/github.com/lozaeric/dupin/users-api
    command: go run main.go
    ports:
     - "8082:8080"
    volumes:
     - ./users-api:/go/src/github.com/lozaeric/dupin/users-api
    environment:
     - ENV=production
     - SECRET_JWT='in the hall of the mountain king'
    depends_on:
     - redis
  metric-collector:
    image: golang:1.9.2
    working_dir: /go/src/github.com/lozaeric/dupin/metric-collector
    command: go run main.go
    ports:
     - "8090:8080"
    volumes:
     - ./metric-collector:/go/src/github.com/lozaeric/dupin/metric-collector
    environment:
     - ENV=production
  redis:
    image: "redis:4.0.11-alpine"
    command: redis-server --appendonly yes
    ports:
     - "6379:6379"
    volumes:
     - ./data/redis:/data
  mongo:
    image: "mongo:3.6.9-stretch"
    ports:
     - "27017:27017"
    volumes:
     - ./data/db:/data/db