version: '3'
services:
  auth:
    image: golang:1.9.2
    working_dir: /go/src/github.com/lozaeric/dupin/auth-api/apitest
    command: go test -v
    volumes:
     - ./auth-api:/go/src/github.com/lozaeric/dupin/auth-api
    depends_on:
     - redis
  redis:
    image: "redis:4.0.11-alpine"
    ports:
     - "6379:6379"
    logging:
     driver: none
