version: '3'
services:
  users:
    image: golang:1.9.2
    working_dir: /go/src/github.com/lozaeric/dupin/users-api
    command: go run main.go
    ports:
     - "8081:8081"
    volumes:
     - ./users-api:/go/src/github.com/lozaeric/dupin/users-api
    environment:
     - ENV=production
    depends_on:
     - redis
  redis:
    image: "redis:4.0.11-alpine"
    command: redis-server --appendonly yes
    ports:
     - "6379:6379"
    volumes:
     - ./data/redis:/data
  mongo:
    image: "mongo:3.6.9-stretch"
    ports:
     - "27017:27017"
    volumes:
     - ./data/db:/data/db